language: node_js

branches:
    only:
        - master

node_js:
    - node
    - 16
    - 14
    - 12

after_script:
    - npm run test-coverage
    - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
    - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
